import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";
import { Resend } from 'resend';
import { InviteEmail } from '@/components/emails/invite-email';

export const dynamic = 'force-dynamic';

export async function POST(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const body = await request.json();
    const { 
      name, 
      email, 
      phone, 
      startDate, 
      endDate, 
      rentAmount, 
      depositAmount 
    } = body;

    if (!name || !email || !startDate || !rentAmount) {
      return NextResponse.json(
        { error: "Mangler påkrevde felt" },
        { status: 400 }
      );
    }

    // Fetch unit details for email
    const unit = await prisma.unit.findUnique({
      where: { id: params.id },
      include: { property: true }
    });

    if (!unit) {
      return NextResponse.json(
        { error: "Enhet ikke funnet" },
        { status: 404 }
      );
    }

    // 1. Find or create tenant user
    // In a real app, we would integrate with Supabase Auth here to invite the user.
    // For this MVP, we will try to find a user by email in our DB, or create a placeholder.
    let tenant = await prisma.user.findUnique({
      where: { email },
    });

    if (!tenant) {
      // Create a placeholder user
      tenant = await prisma.user.create({
        data: {
          email,
          name,
          role: "TENANT",
          // Supabase ID would normally be linked here after they register/login
          // For now we might need a dummy ID or handle this constraint
          // Assuming 'id' is a UUID generated by database or provided. 
          // If our schema uses UUID default, this is fine.
          // However, our schema might expect a Supabase ID.
          // Let's assume we can create it. If id is string @id, we might need to provide it if not default uuid()
        },
      });
    }

    // 2. Create Lease Contract
    const contract = await prisma.leaseContract.create({
      data: {
        unitId: params.id,
        tenantId: tenant.id,
        startDate: new Date(startDate),
        endDate: endDate ? new Date(endDate) : null,
        rentAmount: Number(rentAmount),
        depositAmount: Number(depositAmount),
        status: "DRAFT",
      },
    });

    // 3. Send Email
    if (process.env.RESEND_API_KEY) {
      const resend = new Resend(process.env.RESEND_API_KEY);
      try {
        const loginUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/login`;
        
        await resend.emails.send({
          from: 'Eiendom <onboarding@resend.dev>', // Use resend.dev for testing if domain not verified, or user's domain
          to: email,
          subject: 'Invitasjon til leieforhold',
          react: InviteEmail({
            tenantName: name,
            propertyName: unit.property.name,
            unitName: unit.name,
            loginUrl,
            rentAmount: Number(rentAmount),
            startDate: new Date(startDate).toLocaleDateString('no-NO'),
          }),
        });
        console.log("Email sent successfully to", email);
      } catch (emailError) {
        console.error("Failed to send email:", emailError);
        // We don't block the response if email fails, but we might want to inform client?
        // For now, let's just log it.
      }
    } else {
      console.log("RESEND_API_KEY missing, skipping email send");
    }

    return NextResponse.json(contract);
  } catch (error) {
    console.error("Invite error:", error);
    return NextResponse.json(
      { error: "Kunne ikke opprette invitasjon" },
      { status: 500 }
    );
  }
}
