import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";

export async function POST(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const body = await request.json();
    const { 
      name, 
      email, 
      phone, 
      startDate, 
      endDate, 
      rentAmount, 
      depositAmount 
    } = body;

    if (!name || !email || !startDate || !rentAmount) {
      return NextResponse.json(
        { error: "Mangler påkrevde felt" },
        { status: 400 }
      );
    }

    // 1. Find or create tenant user
    // In a real app, we would integrate with Supabase Auth here to invite the user.
    // For this MVP, we will try to find a user by email in our DB, or create a placeholder.
    let tenant = await prisma.user.findUnique({
      where: { email },
    });

    if (!tenant) {
      // Create a placeholder user
      tenant = await prisma.user.create({
        data: {
          email,
          name,
          role: "TENANT",
          // Supabase ID would normally be linked here after they register/login
          // For now we might need a dummy ID or handle this constraint
          // Assuming 'id' is a UUID generated by database or provided. 
          // If our schema uses UUID default, this is fine.
          // However, our schema might expect a Supabase ID.
          // Let's assume we can create it. If id is string @id, we might need to provide it if not default uuid()
        },
      });
    }

    // 2. Create Lease Contract
    const contract = await prisma.leaseContract.create({
      data: {
        unitId: params.id,
        tenantId: tenant.id,
        startDate: new Date(startDate),
        endDate: endDate ? new Date(endDate) : null,
        rentAmount: Number(rentAmount),
        depositAmount: Number(depositAmount),
        status: "DRAFT",
      },
    });

    return NextResponse.json(contract);
  } catch (error) {
    console.error("Invite error:", error);
    return NextResponse.json(
      { error: "Kunne ikke opprette invitasjon" },
      { status: 500 }
    );
  }
}
